import { Provider } from "@angular/core";
import { authToken } from "./tokens/auth.token";
import { AuthImpRepository } from "@infra/repositories/auth.imp-repository";
import { specialityToken } from "./tokens/speciality.token";
import { SpecialityImpRepository } from "@infra/repositories/speciality.imp-repository";
import { healthProviderToken } from "./tokens/health-provider.token";
import { HealthProviderImpRepository } from "@infra/repositories/health-provider.imp-repository";
import { medicalOfficeToken } from "./tokens/medical-office.token";
import { MedicalOfficeImpRepository } from "@infra/repositories/medical-office.imp-repository";
import { scheduleToken } from "./tokens/schedule.token";
import { ScheduleImpRepository } from "@infra/repositories/schedule.imp-repository";
import { patientToken } from "./tokens/patient.token";
import { PatientImpRepository } from "@infra/repositories/patient.imp-repository";
import { notesToken } from "./tokens/notes.token";
import { NotesImpRepository } from "@infra/repositories/notes.imp-repository";
import { medicalMetricsToken } from "./tokens/medical-metrics.token";
import { MedicalMetricsImpRepository } from "@infra/repositories/medical-metrics.imp-repository";
import { healthProviderScheduleToken } from "./tokens/health-provider-schedule.token";
import { HealthProviderScheduleImpRepository } from "@infra/repositories/health-provider-schedule.imp-repository";
import { healthProviderExceptionsToken } from "./tokens/health-provider-exceptions.token";
import { HealthProviderExceptionsImpRepository } from "@infra/repositories/health-provider-exceptions.imp-repository";
import { subscriptionToken } from "./tokens/subscription.token";
import { SubscriptionImpRepository } from "@infra/repositories/subscription.imp-repository";
import { planToken } from "./tokens/plan.token";
import { PlanImpRepository } from "@infra/repositories/plan.imp-repository";
import { paymentToken } from "./tokens/payment.token";
import { PaymentImpRepository } from "@infra/repositories/payment.imp-repository";
import { tenantToken } from "./tokens/tenant.token";
import { TenantImpRepository } from "@infra/repositories/tenant.imp-repository";

export const diProvider: Provider[] = [
  { provide: authToken, useClass: AuthImpRepository },
  { provide: specialityToken, useClass: SpecialityImpRepository },
  { provide: healthProviderToken, useClass: HealthProviderImpRepository },
  { provide: medicalOfficeToken, useClass: MedicalOfficeImpRepository },
  { provide: scheduleToken, useClass: ScheduleImpRepository },
  { provide: patientToken, useClass: PatientImpRepository },
  { provide: notesToken, useClass: NotesImpRepository },
  { provide: medicalMetricsToken, useClass: MedicalMetricsImpRepository },
  { provide: healthProviderScheduleToken, useClass: HealthProviderScheduleImpRepository },
  { provide: healthProviderExceptionsToken, useClass: HealthProviderExceptionsImpRepository },
  { provide: subscriptionToken, useClass: SubscriptionImpRepository },
  { provide: planToken, useClass: PlanImpRepository },
  { provide: paymentToken, useClass: PaymentImpRepository },
  { provide: tenantToken, useClass: TenantImpRepository }
]